### ISSUE TITLE
VersionConflict error in PyLS

### ISSUE THREAD

**Issue by carloacerbi** [spyder-ide/spyder#9825]
### What steps will reproduce the problem?

launching spyder
I just installed the version 4.0.0b3 and when I start it I get this message
how can I solve it ? 
thanks

### Traceback
```python-traceback
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pyls\python_ls.py", line 161, in m_initialize
    processId, _kwargs.get('capabilities', {}))
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pyls\config\config.py", line 53, in __init__
    entry_point.load()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    self.require(*args, **kwargs)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2347, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
```

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please post the output of

    conda list

to see what can be happening in your case.

**Comment by carloacerbi** [comment]
# packages in environment at C:\Users\Admin\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.11                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.2                    py37_0
appdirs                   1.4.3            py37h28b3542_0
argh                      0.26.2                py37_1001    spyder-ide
asn1crypto                0.24.0                   py37_0
astroid                   2.0.4                    py37_0
astropy                   3.0.4            py37hfa6e2cd_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
automat                   0.7.0                    py37_0
autopep8                  1.4.4                      py_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.6.3                    py37_0
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
blaze                     0.11.3                   py37_0
bleach                    2.1.4                    py37_0
blosc                     1.14.4               he51fdeb_0
bokeh                     0.13.0                   py37_0
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
click                     6.7                      py37_0
cloudpickle               0.5.5                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.3.9                    py37_0
comtypes                  1.1.7                    py37_0
conda                     4.7.5                    py37_0
conda-build               3.15.1                   py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.3.10                   py37_0
console_shortcut          0.1.1                         3
constantly                15.1.0           py37h28b3542_0
contextlib2               0.5.5                    py37_0
cryptography              2.7              py37h7a1dbc1_0
curl                      7.64.1               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.28.5           py37h6538335_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      0.19.1                   py37_0
dask-core                 0.19.1                   py37_0
datashape                 0.5.4                    py37_1
decorator                 4.3.0                    py37_0
defusedxml                0.5.0                    py37_1
diff-match-patch          20181111                   py_0    spyder-ide
distributed               1.23.1                   py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
filelock                  3.0.8                    py37_0
flask                     1.0.2                    py37_1
flask-cors                3.0.6                    py37_0
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.6            py37hfa6e2cd_0
glob2                     0.6                      py37_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
hyperlink                 18.0.0                   py37_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py37_0
imageio                   2.4.1                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.17                     py37_1
incremental               17.5.0                   py37_0
intel-openmp              2019.0                      118
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   6.5.0                    py37_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.4                    py37_0
itsdangerous              0.24                     py37_1
jdcal                     1.4                      py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.3                    py37_0
jupyter_console           5.2.0                    py37_1
jupyter_core              4.4.0                    py37_0
jupyterlab                0.35.4           py37hf63ae98_0
jupyterlab_server         0.2.0                    py37_0
keyring                   13.2.1                   py37_0
kiwisolver                1.0.1            py37h6538335_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libarchive                3.3.3                h0643e63_5
libcurl                   7.64.1               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.24.0           py37h6538335_0
locket                    0.2.0                    py37_1
lxml                      4.2.5            py37hef2cd61_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py37hfa6e2cd_1
matplotlib                2.2.3            py37hd159220_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.14           py37hfa6e2cd_0
mistune                   0.8.3            py37hfa6e2cd_1
mkl                       2018.0.3                      1
mkl-service               1.1.2            py37hb217b18_5
mkl_fft                   1.0.4            py37h1e22a9b_1
mkl_random                1.0.1            py37h77b88f5_1
more-itertools            4.3.0                    py37_0
mpmath                    1.0.0                    py37_2
msgpack-python            0.5.6            py37he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.0                    py37_1
nbformat                  4.4.0                    py37_0
networkx                  2.1                      py37_0
nltk                      3.3.0                    py37_0
nose                      1.3.7                    py37_2
notebook                  5.7.8                    py37_0
numba                     0.39.0           py37h830ac7b_0
numexpr                   2.6.8            py37h9ef55f4_0
numpy                     1.15.1           py37hc27ee41_0
numpy-base                1.15.1           py37h8128ebf_0
numpydoc                  0.8.0                    py37_0
odo                       0.5.1                    py37_0
olefile                   0.46                     py37_0
openpyxl                  2.5.6                    py37_0
openssl                   1.1.1c               he774522_1
packaging                 17.1                     py37_0
pandas                    0.23.4           py37h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
partd                     0.3.8                    py37_0
path.py                   11.1.0                   py37_0
pathlib2                  2.3.2                    py37_0
pathtools                 0.1.2                      py_1    spyder-ide
patsy                     0.5.0                    py37_0
pep8                      1.7.1                    py37_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.4                    py37_0
pillow                    5.2.0            py37h08bbbbd_0
pip                       10.0.1                   py37_0
pkginfo                   1.4.2                    py37_1
pluggy                    0.7.1            py37h28b3542_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
prometheus_client         0.3.1            py37h28b3542_0
prompt_toolkit            1.0.15                   py37_0
psutil                    5.4.7            py37hfa6e2cd_0
py                        1.6.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pyasn1                    0.4.4            py37h28b3542_0
pyasn1-modules            0.2.2                    py37_0
pycodestyle               2.4.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.18                     py37_1
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.3         py37h7a1dbc1_0
pydocstyle                3.0.0                    py37_0
pyflakes                  2.0.0                    py37_0
pygments                  2.2.0                    py37_0
pylint                    2.1.1                    py37_0
pyodbc                    4.0.24           py37h6538335_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.2.0                    py37_1
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37he6f6034_0
pytest                    3.8.0                    py37_0
pytest-arraydiff          0.2              py37h39e3cac_0
pytest-astropy            0.4.0                    py37_0
pytest-doctestplus        0.1.3                    py37_0
pytest-openfiles          0.3.0                    py37_0
pytest-remotedata         0.3.0                    py37_0
python                    3.7.0                hea74fb7_0
python-dateutil           2.7.3                    py37_0
python-jsonrpc-server     0.1.2                      py_0    spyder-ide
python-language-server    0.27.0                   py37_0    spyder-ide
python-libarchive-c       2.8                      py37_8
pytz                      2018.5                   py37_0
pywavelets                1.0.0            py37h452e1ab_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.4                    py37_0
pyxdg                     0.26                       py_0    spyder-ide
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qdarkstyle                2.7                        py_0    spyder-ide
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.7                    py37_1
qtconsole                 4.5.1                      py_0
qtpy                      1.5.0                    py37_0
requests                  2.19.1                   py37_0
rope                      0.11.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.14.0           py37h6538335_1
scikit-learn              0.19.2           py37heebcf9a_0
scipy                     1.1.0            py37h4f6bf74_1
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
service_identity          17.0.0           py37h28b3542_0
setuptools                40.2.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.11.0                   py37_1
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.0.1                    py37_0
sortedcontainers          2.0.5                    py37_0
soupsieve                 1.8                      py37_0
sphinx                    1.7.9                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    4.0.0b3                  py37_0    spyder-ide
spyder-kernels            1.4.0                    py37_0    spyder-ide
sqlalchemy                1.2.11           py37hfa6e2cd_0
sqlite                    3.28.0               he774522_0
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.1.1                    py37_0
tblib                     1.3.2                    py37_0
terminado                 0.8.1                    py37_1
testpath                  0.3.1                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py37_0
tornado                   5.1              py37hfa6e2cd_0
tqdm                      4.26.0           py37h28b3542_0
traitlets                 4.3.2                    py37_0
twisted                   18.7.0           py37hfa6e2cd_1
unicodecsv                0.14.1                   py37_0
urllib3                   1.23                     py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
watchdog                  0.9.0                    py37_1    spyder-ide
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.31.1                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.0.1                    py37_1
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py37hfa6e2cd_2
xlrd                      1.1.0                    py37_1
xlsxwriter                1.1.0                    py37_0
xlwings                   0.11.8                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
yapf                      0.27.0                     py_0
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py37_0
zipp                      0.5.1                      py_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py37_1
zope.interface            4.5.0            py37hfa6e2cd_0
zstd                      1.3.7                h508b16e_0

**Comment by carloacerbi** [comment]
here we go, thanks a lot

**Comment by AndreaGierisch** [comment]
Hi, I get the same error message. And as I have less packages installed, I thought it maybe could help if I also post my ouptut of `conda list`:
```
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2                py36_1001    spyder-ide
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.2.5                    py36_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
autopep8                  1.4.4                      py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
basemap                   1.2.0            py36hf62cb97_3    conda-forge
bcrypt                    3.1.6            py36h516909a_1    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cartopy                   0.17.0          py36h0aa2c8f_1004    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
cftime                    1.0.3.4         py36hd352d35_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cloudpickle               1.2.1                      py_0    conda-forge
cmocean                   2.0                        py_1    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
cryptography              2.7              py36h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
diff-match-patch          20181111                   py_0    spyder-ide
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            h6f030ca_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1100    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.18                     py36_0    conda-forge
ipykernel                 5.1.1            py36h24bf2e0_0    conda-forge
ipython                   7.6.1            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py36_0    conda-forge
jedi                      0.14.0                   py36_0    conda-forge
jeepney                   0.4                        py_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keyring                   19.0.2                   py36_0    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.4.1            py36h516909a_0    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libnetcdf                 4.6.2             h056eaf5_1002    conda-forge
libopenblas               0.3.6                h6e990d7_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                3.1.1                    py36_0    conda-forge
matplotlib-base           3.1.1            py36hfd891ef_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.1.2          py36h73a1b54_1    conda-forge
numpy                     1.16.4           py36h95a1406_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.6                h6e990d7_4    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
owslib                    0.18.0                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.6.0                    py36_0    conda-forge
parso                     0.5.0                      py_0    conda-forge
pathtools                 0.1.2                      py_1    spyder-ide
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    6.0.0            py36he7afcd5_0    conda-forge
pip                       19.1.1                   py36_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
proj4                     5.2.0             he1b5a44_1003    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py36h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pydocstyle                2.1.1                 py36_1000    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pykdtree                  1.3.1           py36h3010b51_1002    conda-forge
pylint                    2.3.1                    py36_0    conda-forge
pynacl                    1.3.0           py36h14c3975_1000    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py36h516909a_1002    conda-forge
pyqt                      5.9.2            py36hcca6a23_0    conda-forge
pyrsistent                0.15.3           py36h516909a_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-jsonrpc-server     0.1.2                      py_0    spyder-ide
python-language-server    0.28.0                   py36_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyxdg                     0.26                       py_0    spyder-ide
pyyaml                    5.1.1            py36h516909a_0    conda-forge
pyzmq                     18.0.2           py36hc4ba49a_0    conda-forge
qdarkstyle                2.7                        py_0    spyder-ide
qt                        5.9.7                h52cfd70_2    conda-forge
qtawesome                 0.5.7              pyh8a2030e_0    conda-forge
qtconsole                 4.5.1                      py_0    conda-forge
qtpy                      1.8.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py36_0    conda-forge
rope                      0.14.0                     py_0    conda-forge
scipy                     1.3.0            py36h921218d_0    conda-forge
secretstorage             3.1.1                    py36_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
shapely                   1.6.4           py36h06cd6f9_1005    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.9.0                      py_0    conda-forge
sphinx                    2.1.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
spyder                    4.0.0b3                  py36_0    spyder-ide
spyder-kernels            1.4.0                    py36_0    spyder-ide
sqlite                    3.28.0               hcee41ef_1    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.4.0            py36h516909a_0    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
viscm                     0.7                pyh24bf2e0_0    conda-forge
watchdog                  0.9.0                    py36_1    spyder-ide
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
wrapt                     1.11.2           py36h516909a_0    conda-forge
wurlitzer                 1.0.3                    py36_0    conda-forge
xarray                    0.12.2                     py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zipp                      0.5.1                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

**Comment by ccordoba12** [comment]
@AndreaGierisch, the error report will be improved in beta4, so please update when that version is out (in a couple of days) and report here the VersionConflict error you're getting.

**Comment by AndreaGierisch** [comment]
This is the error message I get with beta4:
```pkg_resources.VersionConflict: (jedi 0.14.0 (/home/.../.conda/envs/.../lib/python3.6/site-packages), Requirement.parse('jedi!=0.14.0,<0.15,>=0.13.2'))  RuntimeWarning, ```

`conda list` shows this for jedi:
`jedi                      0.14.0                   py36_0    conda-forge`

**Comment by ccordoba12** [comment]
Thanks for reporting back! That was the right fix indeed!

**Comment by ccordoba12** [comment]
I think we can say this is solved now.
