### ISSUE TITLE
pyqt5 < 5.13 in reqirements (update reqirement in spyder beta)

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#9829]
after updating today to git version of beta I am getting

`ERROR: spyder 4.0.0.dev0 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.0 which is incompatible.`

but before I was using spyder beta (from mid-June) with pyqt 5.13 and everything was ok. The requirements <5.13 is caused by a specific error or there is other specific reason for it?

**Comment by ccordoba12** [comment]
I'm sorry but we're very conservative with this requirement, so we're going to change it soon (probably in a month or two, but certainly not now).

**Comment by cadop** [comment]
Is it not possible to run spyder and do python development  with qt then?

**Comment by ccordoba12** [comment]
You need to create two virtualenvs for that.

**Comment by ccordoba12** [comment]
Yes, it is.

**Comment by danieltomasz** [comment]
Any chance for changing this constraint in the next point release?

**Comment by ccordoba12** [comment]
Maybe for 4.1.0, but certainly not for 4.0.2 (which is going to be our next release).

**Comment by epfalzer** [comment]
I am sad to see this is still a requirement for 4.1.3. I am running into more and more packages upgrading to use 5.14 that I cannot use because of spyder. Is it a testing thing where it may work but testing is not complete and you wish to remain stable? Can a user override this and "roll the dice"?

**Comment by jacobcurtis24** [comment]
Any update on this? I need to use PyQt>=5.13 as the resolution of this bug https://stackoverflow.com/questions/60828957/adding-more-than-one-property-to-a-gui-built-with-qt-designer-causes-systemerror is critical for me.

**Comment by ccordoba12** [comment]
@jacobcurtis24, please use two envs: one for Spyder and one to run your code. The second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) explains in detail how to do it.

**Comment by jacobcurtis24** [comment]
@ccordoba12 I apologize for not making this clear in my previous comment, but the code I am maintaining (and transitioning from Python 2.7 to 3.7) imports several modules from Spyder to make a help/documentation UI element. So my application requires both Spyder and PyQt>=5.13 (for other UI elements) to function. Until then, I have to remove the documentation module or remain on Python 2.7.

**Comment by ccordoba12** [comment]
Sorry but support for PyQt >= 5.13 will come (maybe) in our 4.2.2 version, to be released in two months; or in Spyder 5 (for sure), to be released next April.

**Comment by jacobcurtis24** [comment]
@ccordoba12 Ah, too bad. Thanks for the update though!
