### ISSUE TITLE
Variable explorer: Sorting not working

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9835]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/syder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Sorting is not working in Variable explorer on latest master. Nothing happens when I click the column headings, so it is always sorted in ascending order on the first column.

### What steps reproduce the problem?

1. Click on column headings

### What is the expected output? What do you see instead?
Variables are sorted (as in Spyder 3).

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
Thanks for the report. @dalthviz could you take a look? it might be related to some of your earlier work.

**Comment by dalthviz** [comment]
@goanpeca I think this is related with spyder-ider/spyder#5764 and the use of a custom `QHeaderView`. In spyder-ide/spyder#9384 I fixed this by adding `setSectionsClickable(True)` in the `BaseHeaderView`, should I create a PR with just this fix or wait to PR #9384 to be merged?

**Comment by goanpeca** [comment]
Well I think it makes sense to open a new PR to add a regression test so we can catch this in the future if it breaks again. I am not sure if adding this test to #9384 makes sense.

Thoughts?

**Comment by dalthviz** [comment]
I'm going to open a PR with the fix and try to add a test for this :+1:
