### ISSUE TITLE
Spyder crashes when creating new project

### ISSUE THREAD

**Issue by arnyeinstein** [spyder-ide/spyder#9841]
## Problem Description
Starting a new project (either in a new or in an existing directory) causes Spyder 4.0.3b to hang. I have to kill the application and delete the generated spyder project directory to start normally.
I have reinstalled Spyder and reset the program (WPython 3.6, with pip).

* Spyder version:  Spyder 4.0.0b3 , Python 3.6.8 64-bit | Qt 5.12.1 | PyQt5 5.12 | Windows 10 

### Dependencies
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)

Cheers
Renger

**Comment by ccordoba12** [comment]
> Starting a new project (either in a new or in an existing directory) causes Spyder 4.0.3b to hang

We need something more concrete than this to understand what's happening in your case. Please start Spyder from a terminal with this command

    spyder --debug-info verbose --debug-output file

and upload the generated `spyder-debug.log` file here. Thanks!

**Comment by arnyeinstein** [comment]
If I run that command, spyder starts but keeps hanging (not responding) and when I kill spyder, there is no log. I killed, before starting spyder, all python and qt instances in the task manager.

**Comment by ccordoba12** [comment]
Then there's has to be some output in the console where you started Spyder.  If that's the case, please post it.

**Comment by tstreibl** [comment]
I have exactly the same problem after upgrading spyder to beta 3 with "pip install --pre -U" spyder from WinPython 3.7.2.0-64bit. Everything works like a charm except creating or opening a project. Spyder hangs. I don't get neither a log file nor an output in the console (see screenshot). A .spyproject folder with the attached files in it will be created. After killing spyder I have to delete this folder to avoid that spyder hangs up again when I restart it. 
![screenshot](https://user-images.githubusercontent.com/32412085/61386909-65ae9d00-a8b5-11e9-8449-53d3ba626b05.jpg)

[spyproject.zip](https://github.com/spyder-ide/spyder/files/3402475/spyproject.zip)

**Comment by ccordoba12** [comment]
@dalthviz, are you able to reproduce this on Windows?

**Comment by dalthviz** [comment]
@ccordoba12 I couldn't reproduce this one using pip through conda. This is the packages list of the env where I tested:

### conda list
<details>
<pre>
# packages in environment at C:\Users\Daniel\Anaconda3\envs\pipprojects:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
argh                      0.26.2                   pypi_0    pypi
asn1crypto                0.24.0                   pypi_0    pypi
astroid                   2.2.5                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   pypi_0    pypi
autopep8                  1.4.4                    pypi_0    pypi
babel                     2.7.0                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bcrypt                    3.1.7                    pypi_0    pypi
bleach                    3.1.0                    pypi_0    pypi
certifi                   2019.6.16                py36_0
cffi                      1.12.3                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.2.1                    pypi_0    pypi
colorama                  0.4.1                    pypi_0    pypi
cryptography              2.7                      pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
diff-match-patch          20181111                 pypi_0    pypi
docutils                  0.14                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
helpdev                   0.6.10                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imagesize                 1.1.0                    pypi_0    pypi
importlib-metadata        0.18                     pypi_0    pypi
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.6.1                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jedi                      0.13.3                   pypi_0    pypi
jinja2                    2.10.1                   pypi_0    pypi
jsonschema                3.0.1                    pypi_0    pypi
jupyter-client            5.3.1                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
keyring                   19.0.2                   pypi_0    pypi
lazy-object-proxy         1.4.1                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
nbconvert                 5.5.0                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
numpydoc                  0.9.1                    pypi_0    pypi
packaging                 19.0                     pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
paramiko                  2.6.0                    pypi_0    pypi
parso                     0.5.1                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.1.1                   py36_0
pluggy                    0.12.0                   pypi_0    pypi
prompt-toolkit            2.0.9                    pypi_0    pypi
psutil                    5.6.3                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycodestyle               2.5.0                    pypi_0    pypi
pycparser                 2.19                     pypi_0    pypi
pydocstyle                4.0.0                    pypi_0    pypi
pyflakes                  2.1.1                    pypi_0    pypi
pygments                  2.4.2                    pypi_0    pypi
pylint                    2.3.1                    pypi_0    pypi
pynacl                    1.3.0                    pypi_0    pypi
pyparsing                 2.4.0                    pypi_0    pypi
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.3                   pypi_0    pypi
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                    pypi_0    pypi
python-jsonrpc-server     0.2.0                    pypi_0    pypi
python-language-server    0.27.0                   pypi_0    pypi
pytz                      2019.1                   pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pyyaml                    5.1.1                    pypi_0    pypi
pyzmq                     18.0.2                   pypi_0    pypi
qdarkstyle                2.7                      pypi_0    pypi
qtawesome                 0.5.7                    pypi_0    pypi
qtconsole                 4.5.1                    pypi_0    pypi
qtpy                      1.8.0                    pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
rope                      0.14.0                   pypi_0    pypi
setuptools                41.0.1                   py36_0
six                       1.12.0                   pypi_0    pypi
snowballstemmer           1.9.0                    pypi_0    pypi
sphinx                    2.1.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
spyder                    4.0.0b3                  pypi_0    pypi
spyder-kernels            1.4.0                    pypi_0    pypi
sqlite                    3.29.0               he774522_0
testpath                  0.4.2                    pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
typed-ast                 1.4.0                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
watchdog                  0.9.0                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.11.2                   pypi_0    pypi
yapf                      0.28.0                   pypi_0    pypi
zipp                      0.5.2                    pypi_0    pypi
</pre>
</details>

### pip list
<details>
<pre>
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
argh                          0.26.2
asn1crypto                    0.24.0
astroid                       2.2.5
atomicwrites                  1.3.0
attrs                         19.1.0
autopep8                      1.4.4
Babel                         2.7.0
backcall                      0.1.0
bcrypt                        3.1.7
bleach                        3.1.0
certifi                       2019.6.16
cffi                          1.12.3
chardet                       3.0.4
cloudpickle                   1.2.1
colorama                      0.4.1
cryptography                  2.7
decorator                     4.4.0
defusedxml                    0.6.0
diff-match-patch              20181111
docutils                      0.14
entrypoints                   0.3
future                        0.17.1
helpdev                       0.6.10
idna                          2.8
imagesize                     1.1.0
importlib-metadata            0.18
ipykernel                     5.1.1
ipython                       7.6.1
ipython-genutils              0.2.0
isort                         4.3.21
jedi                          0.13.3
Jinja2                        2.10.1
jsonschema                    3.0.1
jupyter-client                5.3.1
jupyter-core                  4.5.0
keyring                       19.0.2
lazy-object-proxy             1.4.1
MarkupSafe                    1.1.1
mccabe                        0.6.1
mistune                       0.8.4
nbconvert                     5.5.0
nbformat                      4.4.0
numpydoc                      0.9.1
packaging                     19.0
pandocfilters                 1.4.2
paramiko                      2.6.0
parso                         0.5.1
pathtools                     0.1.2
pexpect                       4.7.0
pickleshare                   0.7.5
pip                           19.1.1
pluggy                        0.12.0
prompt-toolkit                2.0.9
psutil                        5.6.3
ptyprocess                    0.6.0
pycodestyle                   2.5.0
pycparser                     2.19
pydocstyle                    4.0.0
pyflakes                      2.1.1
Pygments                      2.4.2
pylint                        2.3.1
PyNaCl                        1.3.0
pyparsing                     2.4.0
PyQt5                         5.12.3
PyQt5-sip                     4.19.18
PyQtWebEngine                 5.12.1
pyrsistent                    0.15.3
python-dateutil               2.8.0
python-jsonrpc-server         0.2.0
python-language-server        0.27.0
pytz                          2019.1
pywin32-ctypes                0.2.0
PyYAML                        5.1.1
pyzmq                         18.0.2
QDarkStyle                    2.7
QtAwesome                     0.5.7
qtconsole                     4.5.1
QtPy                          1.8.0
requests                      2.22.0
rope                          0.14.0
setuptools                    41.0.1
six                           1.12.0
snowballstemmer               1.9.0
Sphinx                        2.1.2
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
spyder                        4.0.0b3
spyder-kernels                1.4.0
testpath                      0.4.2
tornado                       6.0.3
traitlets                     4.3.2
typed-ast                     1.4.0
urllib3                       1.25.3
watchdog                      0.9.0
wcwidth                       0.1.7
webencodings                  0.5.1
wheel                         0.33.4
wincertstore                  0.2
wrapt                         1.11.2
yapf                          0.28.0
zipp                          0.5.2
</pre>
</details>

**Comment by ccordoba12** [comment]
Thanks @dalthviz!

@arnyeinstein, @tstreibl, please report this problem in WinPython because it's not caused by Spyder itself:

https://github.com/winpython/winpython/issues/

Most probably is caused by PyQt 5.13, which we don't support yet.
