### ISSUE TITLE
spyder debugging error

### ISSUE THREAD

**Issue by yangtongs** [spyder-ide/spyder#9843]
### What steps will reproduce the problem?

My code can run normal. But when I used spyder to debug my code, the spyder console reported this problem. 

"**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 218: invalid continuation byte"

also, my code can run and debug normal in other IDE, like pycharm. I want some help, and can contact me by email: 912878338@qq.com 

thanks!

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please post the simplest possible example that generates the problem you're seeing (don't post your entire code because most probably we won't be able to run it).

That's the only way we can help you with your problem.

**Comment by yangtongs** [comment]
Hello,

Thank you very much for replying to my email.

I have solved this problem today by deleting the spyder configuration folder in my user directory.

Thanks again for your reply!



------------------
此致 
                                                                                   杨同帅


 




------------------ 原始邮件 ------------------
发件人: "Carlos Cordoba"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 下午5:48
收件人: "spyder-ide/spyder"<spyder@noreply.github.com>;
抄送: "﹏獨行、浹"<912878338@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [spyder-ide/spyder] spyder debugging error (#9843)




Please post the simplest possible example that generates the problem you're seeing (don't post your entire code because most probably we won't be able to run it).
 
That's the only way we can help you with your problem.
