### ISSUE TITLE
IPython console stuck in "connecting to kernel"

### ISSUE THREAD

**Issue by sujithkumar83** [spyder-ide/spyder#9853]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I start Spyder from Anaconda3 or directly from Windows Menu I find the console stuck with "Connecting to kernal..." message. I can connect using "Connect to an existing kernel"--> Browse--> {selecting the kernel} and it opens in another ipython console

### What steps reproduce the problem?

1. Open Spyder (3.3.6) on Win10 menu/ Open Spyder (3.3.6) thru Anaconda navigator (Anaconda3)
2. 
3. 

### What is the expected output? What do you see instead?
Console 1/A stuck with "Connecting to kernel..." status

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 18.000179767608643

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Win10 Pro, x64

### Dependencies

```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  None (NOK)

```

**Comment by ccordoba12** [comment]
Please start Spyder from the Anaconda Prompt and report any errors you see there.

**Comment by sujithkumar83** [comment]
Thanks for checking. Actually I did another Anaconda install from scratch and the issue went away. Closing the issue.

**Comment by mickeykatz** [comment]
Hello, I (and two other colleagues) am seeing the same exact issues on my machine as detailed above (Console 1/A spins indefinitely with "Connecting to kernel..." status). I tried all the steps recommended above including opening Spyder from my Anaconda Prompt and re-installing Anaconda from scratch and then running `conda update --all`. When running spyder directly from an Anaconda Prompt, I receive the below traceback (it just continues spinning and the kernel dies ~ every 18 seconds).

Please let me know if I can provide any additional information. 

### Paste Traceback/Error Below (if applicable)


```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
 spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 18.02844214439392
WARNING:traitlets:kernel died: 18.028401613235474
WARNING:traitlets:kernel died: 18.02839970588684
WARNING:traitlets:kernel died: 18.028398990631104
WARNING:traitlets:kernel died: 18.028462886810303
WARNING:traitlets:kernel died: 18.028400182724


```


## Versions


* Spyder version: 3.3.6
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro, x64 

### Dependencies


```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
@mickeykatz, please deactivate your firewall/antivirus and try again.

**Comment by myungus** [comment]
I have the same problem described above. I'm working under strict company IT policies which makes it hard to disable firewall/antivirus to test if that fixes the problem. @ccordoba12 would you care explaining why is the kernel connection affected by firewall/antivirus limitations?

**Comment by ccordoba12** [comment]
@myungus, because the kernel is really another Python process to which the Spyder graphical interface communicates using sockets.

So if your firewall/antivirus prevents opening local sockets in your PC, then there's nothing we can about it.

**Comment by Kartikei-12** [comment]
@ccordoba12 I am facing the same issue, and have tried all of the above proposed solution including firewall and antivirus suggestion still cannot get it to work.

I have tried all possible combination of the following:
1. Directly installing spyder through pip install
2. Getting spyder through Anaconda
3. Disabling antivirus/firewall.

**Comment by Kartikei-12** [comment]
@ccordoba12  Finally got issue to solve, I think problem is with Jupyter integrating with spyder for the kernal, I uninstalled jupyter, jupyter-core, jupyter-client and jupyter-console and manually removed any residual files including cached packages.

And reinstalled spyder from scratch and it worked.

**Comment by Tim-K-DFW** [comment]
Same issue - indefinitely stuck on `Connecting to kernel`, tried 3 or 4 times on a clean environment. Tried both `conda install spyder` and `conda install spyder -c conda-forge`. Running this on Windows 10 Pro x64; Python 3.7.6.

Here's the kicker... When installing Spyder initially in a different environment (where it still works), initial install pulled Spyder v3, then after `conda update spyder` it pulled v4. Two or three weeks ago it reversed. Now initial install command pulls v4 (which doesn't work - stuck on Connecting to kernel on startup), but running `conda update spyder` changes it to v3 (which does work). 

And, guys, thank you very much for this great product, nothing else that I tried in Python stack (after working exclusively with RStudio) comes close to Spyder.

**Comment by ccordoba12** [comment]
@Tim-K-DFW, thanks for your kind words! Please wait until we release our next version (4.1.0) in a couple of weeks, which comes with some fixes that could help in this case.

And please also open another issue to track your problem because this one is closed.

**Comment by tanmoy7863** [comment]
please uninstall your antivirus...I have faced the similar issue and by uninstalling the antivirus now spyder is working.

**Comment by aadnankahnn** [comment]
I deleted all existing python copies on my system (2.7, 3.7, 3.8), deleted ANACONDA, rebooted my PC, installed ANACONDA again and then voila, spyder console worked for me.
