### ISSUE TITLE
Missing syntax colouring features

### ISSUE THREAD

**Issue by picatostas** [spyder-ide/spyder#9855]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Class methods not highlighted as in Sublime Text, difficulting code reading.

The color scheme editor only has :

- Normal text
- Comment, not differenciating Docstrings comments
- String, not differenciating Docstrings 
- Number
- Keyword
- Builtin
- Definition
- Instance

### What steps reproduce the problem?

1.  N.A.
2.  N.A.
3.  N.A. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.6.8
* Qt version:  Dunno
* PyQt version: 5.12.3
* Operating System name/version:  Ubuntu 18.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Sorry but we're not planning on adding more tokens to our syntax highlighters for the time being.
