### ISSUE TITLE
Variable explorer error when opening Dataframe with float values

### ISSUE THREAD

**Issue by potterton48** [spyder-ide/spyder#9856]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Variable explorer not working for panda DataFrames with float values

### What steps reproduce the problem?

1. Importing pandas:
 import pandas as pd 
2. Make a simple dataframe with float values:
test=pd.DataFrame([1.2,3.4,5.6])
3. Click on test in Variable explorer

### What is the expected output? What do you see instead?
Should see variable explorer window, instead see an error window.

### Paste Traceback/Error Below (if applicable)
"Spyder was unable to retrieve the value of this variable from the console.

The error mesage was:
UnicodeDecodeError('ascii', b'333333\xf3?333333\x0b@ffffff\x16@', 6, 7, 'ordinal not in range(128)')"

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: MacOS Mojave 10.14.5

### Dependencies

```
IPython >=4.0     :  7.6.0 (OK)
cython >=0.21     :  None (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  None (OK)
```

**Comment by ccordoba12** [comment]
Are you connecting to a Python 2 kernel from your Python 3 installation?

**Comment by potterton48** [comment]
No the console says Python 3.7.0.

**Comment by ccordoba12** [comment]
Then I'd say this is an installation issue because we test the variable explorer as part of our test suite and we haven't encountered this problem nor it has been reported before.

So you have two options:

1. The easiest one is to create a new conda environment, install Spyder there and test the variable explorer in that env.
2. Reinstall Anaconda.

In any case, this is up to you to solve. It was probably introduced by installing packages with either pip or from conda-forge, which you should avoid in the future.
