### ISSUE TITLE
New automatic completion makes it hard to work...

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9871]
## Problem Description
While I in many ways appreciate the new automatic completion stuff, it also introduced a few challenges. Two which I have isolated and lists here.

It is crucial that Ctrl+s is passed through to the editor. It has happened quite a few times that I have edited a file and pressed Ctrl+s, just to later find out that the file is still marked as modified. (One reason for the many test runs for #9870...)

The behavior below is a bit annoying. What happens is that I press backspace one time to many (in this case it is a Mickey Mouse example) and press return as I would like to insert a line break here again. Not sure what the proper solution is here though (except that I am surprised that the completions start with the first letter of the, earlier, next line, which doesn't really make sense).

![autocompletion](https://user-images.githubusercontent.com/8114497/61584134-18dff600-ab43-11e9-89b2-b7a8a860e763.gif)

**Comment by drive-buss** [comment]
I think you can turn it off!

**Comment by ccordoba12** [comment]
@andfoy, please take look at this one.

**Comment by oscargus** [comment]
After some more use I think a way forward may be:

1) Do not show the completions after a backspace as this happens also for other cases, such as deciding to break a line and backspacing to get rid of the trailing space before pressing return.

2) Pass all(?) command keys (Ctrl+.. etc) to the editor. (I can live with that home, end, page up, and page down are not passed through. After all, hard to guess what the user is thinking...)

I also noted a third issue: the completion does not consider case. If there are two completion entries, say foo and FOO, typing foo and pressing enter will lead to FOO (as that is sorted firstly). In fact, foo is not longer shown among the possible completions at that stage. I think that at least exact matches should be considered.

Code for testing:
```
foo = 1
FOO = 2
```
now type `foo`.
