### ISSUE TITLE
Spyder 4.0.0b3 doesn't show initial IPython console output fully

### ISSUE THREAD

**Issue by ilayn** [spyder-ide/spyder#9876]
## Problem Description
Spyder 4.0.0b3 doesn't (re)start kernel console windows fully.

### What steps reproduce the problem?

1. Fire up Spyder and wait for startup take place and wait (seemingly forever).

### What is the expected output? What do you see instead?
The expected output is to have the IPython kernel prompt with the initial messages such as 

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.4.0 -- An enhanced Interactive Python.
In [1] : 
```

However the console window is empty. If you try to enforce a popup, related to this console window however, everything goes back to normal. Here is a gif that I have managed this behavior in a reproducible manner. This is also the initial startup behavior. 

![repro](https://user-images.githubusercontent.com/1303842/61591395-c0ead300-abc6-11e9-9304-eab340539804.gif)

## Versions

* Spyder version: 4.0.0b3
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Win10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.18.0.dev0+4f7d5eb (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.29.7 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
This is an installation problem, probably due to the fact that you're using development versions of some of our dependencies, like Numpy.

Please install Spyder in a clean conda environment and try again.

**Comment by ilayn** [comment]
I am not using conda but I created the same environment except numpy being 1.17 and the same issue is there. That might point to Qt/PyQt mismatch maybe. I'll investigate a bit more.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

If you find more info about this problem, please keep posting it here.

**Comment by ilayn** [comment]
I can't report more than what is available. Outside conda env this is reproducible. But I don't know what else to add.

**Comment by ccordoba12** [comment]
That's why we recommend to use conda instead of pip.

**Comment by ilayn** [comment]
I understand but I have the opposite experience. However in my humble opinion conda cannot be a dependency on spyder. So I guess I need to find the reason one way or the other.
