### ISSUE TITLE
Windows layout does not work properly

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9878]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
While trying to get rid of Python 3.8 deprecation warnings, I realized that floats between 0 and 1 were passed to a function accepting integers. Trying out changing the windows layout, made me realize that it is not working properly. See clip below, especially for Matlab it is clear.
![windowlayoutissues](https://user-images.githubusercontent.com/8114497/61597758-67a99080-ac14-11e9-9e7f-f3762bc56e11.gif)

The problems are: 

As the values are casted to ints, most of them are zero so everything is of the same size.
Using `--debug` reveals the following warning:
`QMainWidget::resizeDocks: all sizes need to be larger than 0` (as can be seen in the beginning of the clip in the terminal).

Changing a layout automatically maximized the window (which maybe is a design choice since it is the same in Spyder 3)

A solution is to simply enter integer values for the ratios, so scale them with e.g 100. I have done that. However, I do not really know if this solves everything as I haven't figured out if this will work with the save feature. (It seems like saved layouts are based on the non-maximized window size, so maybe this is a hint that it is working and it is simply to rescale the ratios.) If someone can shed light on this I can provide a PR. (I tried to read the code, but didn't fully manage to figure out how things were saved and restored.) Seems better than to provide a PR that may be incorrect...

(Somewhat surprisingly, the outline pane in the Spyder layout has about the correct format when added.)

### What steps reproduce the problem?

1. Switch window layout

### What is the expected output? What do you see instead?
At least that the windows layout follows the specified ratios. Ideally, the window shouldn't change maximization status.

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
>A solution is to simply enter integer values for the ratios, so scale them with e.g 100

Yes, this should probably be enough, could you open a PR with that fix?
