### ISSUE TITLE
Saving a file in spyder 4 changes the file permissions

### ISSUE THREAD

**Issue by dbau-igenomix** [spyder-ide/spyder#9882]
## Problem Description
Saving a file in spyder 4 changes the file permissions to 600.

### What steps reproduce the problem?

1. Open file in spyder 
2. Modify file
3. Save file

### What is the expected output? What do you see instead?
File permissions should not change.

* Spyder version: 4.0.0b2
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04 LTS

**Comment by ccordoba12** [comment]
Fixed in beta3, please update.
