### ISSUE TITLE
SymPy color problems

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9885]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
 * [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
It seems like that the default Spyder console have tweaked the LaTeX rendering color:

![image](https://user-images.githubusercontent.com/8114497/61664666-84f16400-acd3-11e9-856d-9f13132783cc.png)

However, in the SymPy console this is not done (the same Integral is there, but printed in black):

![image](https://user-images.githubusercontent.com/8114497/61664774-ca159600-acd3-11e9-9abb-3bd2ccc66e98.png)

When trying to sort this out, I realized a few things.

The reason that the printing is not working in the same way is that an `init_printing()` call shows up from somewhere (although it is not included in the descriptive printout). Compare
`2019-07-22 22:54:36,746 [DEBUG] [traitlets] -> stream: {'name': 'stdout', 'text': "IPython console for SymPy 1.4 (Python 3.7.3-64-bit) (ground types: python)\n\nThese commands were executed:\n>>> from __future__ import division\n>>> from sympy import *\n>>> x, y, z, t = symbols('x y z t')\n>>> k, m, n = symbols('k m n', integer=True)\n>>> f, g, h = symbols('f g h', cls=Function)\n>>> init_printing()\n\nDocumentation can be found at https://docs.sympy.org/1.4/\n\n"}`
and
https://github.com/spyder-ide/spyder/blob/859825153f3df0fe0dc6fc9980affe7c6df837a3/spyder/plugins/ipythonconsole/widgets/shell.py#L200-L209

On a restart, the elusive text is printed in full though:
![image](https://user-images.githubusercontent.com/8114497/61665260-d0f0d880-acd4-11e9-972a-24d97e9ef02c.png)
And the code seemingly handling the restart in Spyder is never called (easily confirmed by changing it, this is where I tried to set the color, quite a few time in different ways...):
https://github.com/spyder-ide/spyder/blob/859825153f3df0fe0dc6fc9980affe7c6df837a3/spyder/plugins/ipythonconsole/widgets/shell.py#L283-L291

Finally, as far as I can tell, it would be better to send the font color to `init_printing` (the difference in clarity is not just from different scaling of the images). The problem is just how to obtain it...
![image](https://user-images.githubusercontent.com/8114497/61665357-0e556600-acd5-11e9-9585-8466be75fa25.png)

I'd be happy to work on this, but I do not really understand where the initialization commands come from. Nor, how the restart is supposed to work. Why is the dedicated Spyder code not called? If I understand it correctly, there is some SymPy/IPython magic (as the LaTeX rendering works without explicit `init_printing`). I know that there are discussions how to have that detect dark background, e.g. https://github.com/ipython/ipython/issues/9451 and https://github.com/sympy/sympy/issues/10655 and maybe the best thing is to fix it there. However, in the meanwhile, one should at least be able to set it to the current font color in the SymPy console.

### What is the expected output? What do you see instead?

Same color in both standard and SymPy console (or even better, use the font color directly).

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by oscargus** [comment]
Good to write down stuff as it sometimes makes you think clearer. The initialization code from the SymPy console comes from:
https://github.com/sympy/sympy/blob/56dceb1974848d97636f2f41c0893c738380e2e2/sympy/interactive/session.py#L10-L17

It is probably possible to modify https://github.com/sympy/sympy/blob/56dceb1974848d97636f2f41c0893c738380e2e2/sympy/interactive/printing.py#L36 to pick up the color (or `'figure.facecolor'` rather, but that may do, or guessing from `colors`). However, this will go into SymPy 1.5.0 with unknown release date, so I guess trying to at least get the same rendering in the SymPy console as the the standard console should be relevant to fix.

**Comment by ccordoba12** [comment]
This is a known issue. See #3798.

**Comment by oscargus** [comment]
Ah, I searched for Sympy (dependencies) but for obvious reasons there were quite a lot of hits...

There are some more issues here as well though, such as why the restart code is not working (as one may expect it to work), the printout of commands not being the same/correct, and the inconsistent behavior between a standard console and a SymPy console. But your call.
