### ISSUE TITLE
Missing space when rendering NumPy docstrings

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#9888]
In NumPy-style docs such as this snippet below:
```
Parameters
----------
some_param : type of this parameter
    Explanation about the parameter
```

Spyder's help renders the type of the parameter without any spacing from the name. Attached is a screenshot highlighting this:
![spyder_format](https://user-images.githubusercontent.com/11860098/61712621-66d14580-ad5f-11e9-84fe-8f25edd652ca.png)

Sphinx itself adds that extra separating space, as can be seen in e.g. the official numpy docs:
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html

**Comment by ccordoba12** [comment]
That's a Sphinx problem and it changes from version to version.

What's your Sphinx version?

**Comment by david-cortes** [comment]
@ccordoba12 : it's Sphinx 2.1.2 (latest stable version). If I pick some random package and build html docs through Sphinx with the alabaster theme, they don't look like they're missing a space.

**Comment by Dan-Patterson** [comment]
Roll back to sphinx 1.8.5  I raised this issue a while ago [https://github.com/spyder-ide/spyder/issues/created_by/Dan-Patterson](url)

**Comment by ccordoba12** [comment]
@Dan-Patterson, your link above doesn't show any issues.

**Comment by Dan-Patterson** [comment]
[https://github.com/spyder-ide/spyder/issues/9527](url)  missed the link... issue 9527.  I have also seen references to pinning to sphinx 1.8.5 with other packages, but I don't have a list.

**Comment by ccordoba12** [comment]
Thanks! I closed that issue in favor of this one because this has a more detailed explanation of the problem.

**Comment by Khalilsqu** [comment]
This bug also affects indentation guides, I modified the indentation guides in a merged PR so that they follow the same level and styling as code folding. If this big is resolved indentation guides should be updated accordingly.

**Comment by ccordoba12** [comment]
@dalthviz, please take care of this one as soon as you can. We need it for @juanis2112's work on improving our docs.
