### ISSUE TITLE
Updating Spyder3 on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by dangerousMoron** [spyder-ide/spyder#9889]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I run `sudo zypper dup` I get the following issue from Spyder

 ```
Problem: spyder3-3.3.5-1.1.noarch requires python3-qtwebengine-qt5 < 5.13, 

but this requirement cannot be provided

  deleted providers: python3-qtwebengine-qt5-5.12-1.4.x86_64

 Solution 1: Following actions will be done:

  deinstallation of spyder3-3.3.5-1.1.noarch
  deinstallation of spyder3-breakpoints-3.3.5-1.1.noarch
  deinstallation of spyder3-dicom-3.3.5-1.1.noarch
  deinstallation of spyder3-hdf5-3.3.5-1.1.noarch
  deinstallation of spyder3-lang-3.3.5-1.1.noarch
  deinstallation of spyder3-profiler-3.3.5-1.1.noarch
  deinstallation of spyder3-pylint-3.3.5-1.1.noarch
  deinstallation of spyder3-breakpoints-lang-3.3.5-1.1.noarch
  deinstallation of spyder3-profiler-lang-3.3.5-1.1.noarch
  deinstallation of spyder3-pylint-lang-3.3.5-1.1.noarch
 Solution 2: keep obsolete python3-qtwebengine-qt5-5.12-1.4.x86_64
 Solution 3: break spyder3-3.3.5-1.1.noarch by ignoring some of its dependencies

```

Running `zypper search -s` yields: 

```
Loading repository data...
Reading installed packages...

S  | Name                    | Type    | Version    | Arch   | Repository           
---+-------------------------+---------+------------+--------+----------------------
i  | python3-qtwebengine-qt5 | package | 5.12-1.4   | x86_64 | (System Packages)    
v  | python3-qtwebengine-qt5 | package | 5.13.0-1.1 | x86_64 | Main Repository (OSS)
v  | python3-qtwebengine-qt5 | package | 5.13.0-1.1 | i586   | Main Repository (OSS)
```

## Versions

* Spyder version: spyder3-3.3.5-1.1
* Python version: 3.7.3
* Qt version: 5.13.0
* PyQt version: 5.13.0
* Operating System name/version: OpenSUSE Tumbleweed

**Comment by bnavigator** [comment]
See https://bugzilla.opensuse.org/show_bug.cgi?id=1141974

Why does Spyder depend on pyqt5 < 5.13?

**Comment by ccordoba12** [comment]
> Why does Spyder depend on pyqt5 < 5.13?

Because several things are failing with it.

I'm closing this because there's nothing we can do about this.

**Comment by bnavigator** [comment]
> Because several things are failing with it.

Can you please elaborate on this a bit? OpenSUSE Tumbleweed does not seem to adhere to the version pinning so far. They might want to reconsider. From the commit log in setup.py it is not obvious, there it appears you just stick to 5.12 for "LTS" reasons.

**Comment by ccordoba12** [comment]
Please see

https://github.com/spyder-ide/spyder/issues/9883

Although that applies to Spyder 4, it probably applies to Spyder 3 too.

Also

https://github.com/spyder-ide/spyder/issues/9811

which applies to Spyder 3.

----

> From the commit log in setup.py it is not obvious, there it appears you just stick to 5.12 for "LTS" reasons.

We're a very small project with lots of users and don't have time to update our entire test suite to support the latest Qt/PyQt versions. What we decided to do is investing our efforts to only be in line with Qt LTS versions.

Besides, the vast majority of our installations (2.5M in 2018) are through Anaconda, which only updates Qt to its LTS versions too.

**Comment by bnavigator** [comment]
Understandable.

Although I experience the mentioned issues neither in Arch (Spyder 3.3.5) nor in Tumbleweed (Spyder 3.3.6) both with Qt 5.13.0
