### ISSUE TITLE
Improve shortcuts table UI

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9891]
Right now there's very hard for people to know that they can customize our keyboard shortcuts in our Preferences. That's because there's no message mentioning that and no UI element signaling the possibility.

To fix this I think that we could do the following:

1. Add this message on top of the shortcuts table:
    > Here you can browse the list of all available shortcuts in Spyder. You can also customize them by clicking on any entry in this table.

2. Change the cursor to be a hand when hovering the shortcuts table and make a single click open the dialog to change shortcuts.

@goanpeca, @jnsebgosselin, what do you think about my suggestions?

**Comment by goanpeca** [comment]
Hi @ccordoba12. I think the message should suffice :-), but i see no harm in adding the hand as well

**Comment by ccordoba12** [comment]
Great! @steff456, please work on implementing my suggestions then.
