### ISSUE TITLE
Apparent autoreload memory leak

### ISSUE THREAD

**Issue by hetfmt** [spyder-ide/spyder#9892]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have just updated Spyder to the latest version, and now I experience the following problem that I have not experienced before:
"Autoreload" takes a long time and consumes all available memory before execution continues when running a file, if the content of the file (module) has been modified. 
A manual (re-)import of the same modified module causes the same problem.
Upon "first" import, e.g. after the kernel has been restarted, everything works as expected.

I have tried to run the same file multiple times in PyCharm, without any problems. But here the console is restarted with every "run" command, so this cannot be compared to the reported bug. Because in Spyder there is also not a problem, if the console is restarted just prior to running the file.

I have not tried "jupyter qtconsole" since I don't know how to do that.

### What steps reproduce the problem?
I tried the following to verify the nature of the problem:
1) Run as file:
```
runfile('<my_path>/loineye_rotation_utility.py', wdir='<my_path>')
```
_Reading images from: XYZ
Creating rectified images...
Subtracting background image..._

2) Re-run the file, without changing anything:
```
runfile('<my_path>/loineye_rotation_utility.py', wdir='<my_path>')
```
_Reading images from: XYZ
Creating rectified images...
Subtracting background image..._

3) Make as single (insignificant) change to the file and re-run:
```
runfile('<my_path>/loineye_rotation_utility.py', wdir='<my_path>')
```
_Reading images from: XYZ
Creating rectified images...
Subtracting background image..._

The output is the same as before, and there are no apparent errors, but rather than taking 10 seconds to complete, it takes more than 5 minutes before the first output is being printed to the console! Also, when inspecting the Windows "Task Manager" I see that the memory consumption increases from 20% to 100% (16 GB), then drops to 74% only to increase to 100% once more. Then memory consumption drops back to the starting level at 20% as execution completes.
During the consumption of memory, CPU load is at 34%, and it only increases to 100% when there is a "step change" in the amount of consumed memory.

4) Make another insignificant change to the file and re-run:
```
runfile('<my_path>/loineye_rotation_utility.py', wdir='<my_path>')
```
Rather than waiting for the process to complete by itself (as the above example) i press the (now red) "Stop the current command" button, and a trace is written to the console before the execution completes with the normal console output:
_Reading images from: XYZ
Creating rectified images...
Subtracting background image..._
The trace is included below.

### What is the expected output? What do you see instead?
As described, I get the expected output  - once the modified module has been reloaded.

### Paste Traceback/Error Below (if applicable)
```python-traceback
[autoreload of loineye_rotation_utility failed: Traceback (most recent call last):
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 450, in superreload
    update_generic(old_obj, new_obj)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 387, in update_generic
    update(a, b)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 357, in update_class
    update_instances(old, new)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 312, in update_instances
    update_instances(old, new, obj.__dict__, visited)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\Tools\Anaconda3\envs\loineye\lib\site-packages\IPython\extensions\autoreload.py", line 302, in update_instances
    visited.update({id(obj):obj})
KeyboardInterrupt
]```

## Versions
* Spyder version: 3.3.6
* Python version: 3.6.8 (64 bit)
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro

### Dependencies
```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is not a problem in Spyder and it's been is discussed here:

https://github.com/ipython/ipython/issues/11817
