### ISSUE TITLE
anaconda spyder an error occurred while starting the kernel. unexpected EOF while parsing

### ISSUE THREAD

**Issue by honey09280** [spyder-ide/spyder#9898]
### Issue Report Checklist
I looked at the relevant issues in the past and followed the trouble shooting steps told in that issue. For example, I tried:

conda update spyder ipykernel tornado pyzmq

conda install -c anaconda spyder ipykernel=4.8.2

But didn't fix the issue.

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Hi,

I recently installed Anaconda 2.7 on my Windows 64 bit Laptop. When I started/opened the spyder notebook from Anaconda, it says:

an error occurred while starting the kernel.

The error is:

Traceback (most recent call last):
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\jupyter_client\manager.py", line 254, in start_kernel
env.update(self.kernel_spec.env or {})
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\utils\ipython\kernelspec.py", line 113, in env
'startup/use_run_file'),
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\config\user.py", line 384, in get
value = ast.literal_eval(value)
File "C:\Users\HONEY\Anaconda2\lib\ast.py", line 49, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "C:\Users\HONEY\Anaconda2\lib\ast.py", line 37, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "", line 0

^
SyntaxError: unexpected EOF while parsing

I haven't typed any code, I just opened spyder(3.3.2) from Anaconda and I see this in the console.

### What steps reproduce the problem?

1. When I open the spyder, it gives error message in the console. Cannot execute any programs because of this issue,.
2. 
3. 

### What is the expected output? What do you see instead?

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\jupyter_client\manager.py", line 254, in start_kernel
env.update(self.kernel_spec.env or {})
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\utils\ipython\kernelspec.py", line 113, in env
'startup/use_run_file'),
File "C:\Users\HONEY\Anaconda2\lib\site‑packages\spyder\config\user.py", line 384, in get
value = ast.literal_eval(value)
File "C:\Users\HONEY\Anaconda2\lib\ast.py", line 49, in literal_eval
node_or_string = parse(node_or_string, mode='eval')
File "C:\Users\HONEY\Anaconda2\lib\ast.py", line 37, in parse
return compile(source, filename, mode, PyCF_ONLY_AST)
File "", line 0

^
SyntaxError: unexpected EOF while parsing

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version:  2.7.10
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 64 bit Laptop

### Dependencies

```
PASTE DEPENDENCIES HERE
```
alabaster 0.7.12
astroid 1.6.6
attrs 19.1.0
Babel 2.7.0
backports-abc 0.5
backports.functools-lru-cache 1.5
backports.shutil-get-terminal-size 1.0.0
bleach 3.1.0
certifi 2019.6.16
chardet 3.0.4
cloudpickle 1.2.1
colorama 0.4.1
configparser 3.7.4
cycler 0.10.0
decorator 4.4.0
defusedxml 0.6.0
docutils 0.15
entrypoints 0.3
enum34 1.1.6
functools32 3.2.3.post2
futures 3.3.0
idna 2.8
imagesize 1.1.0
ipykernel 4.10.0
ipython 5.8.0
ipython-genutils 0.2.0
isort 4.3.21
jedi 0.14.1
Jinja2 2.10.1
jsonschema 3.0.1
jupyter-client 5.3.1
jupyter-core 4.5.0
keyring 18.0.1
kiwisolver 1.1.0
lazy-object-proxy 1.4.1
MarkupSafe 1.1.1
matplotlib 2.2.4
mccabe 0.6.1
mistune 0.8.4
nbconvert 5.5.0
nbformat 4.4.0
numpy 1.16.4
numpydoc 0.9.1
packaging 19.0
pandocfilters 1.4.2
parso 0.5.1
pathlib2 2.3.4
pickleshare 0.7.5
Pillow 6.0.0
pip 19.1.1
prompt-toolkit 1.0.16
psutil 5.6.3
pycodestyle 2.5.0
pyflakes 2.1.1
Pygments 2.4.2
pylint 1.9.5
pyparsing 2.4.0
pyrsistent 0.15.3
python-dateutil 2.8.0
pytz 2019.1
pywin32-ctypes 0.2.0
pyzmq 18.0.2
QtAwesome 0.5.8
qtconsole 4.5.1
QtPy 1.9.0
requests 2.22.0
rope 0.14.0
scandir 1.10.0
setuptools 41.0.1
simplegeneric 0.8.1
singledispatch 3.4.0.3
six 1.12.0
snowballstemmer 1.9.0
Sphinx 1.8.5
sphinxcontrib-websupport 1.1.2
spyder 3.3.6
spyder-kernels 0.5.1
testpath 0.4.2
tornado 5.1.1
traitlets 4.3.2
typing 3.7.4
urllib3 1.25.3
wcwidth 0.1.7
webencodings 0.5.1
wheel 0.33.4
win-unicode-console 0.5
wrapt 1.11.2

Previously I didn't have spyder in python. I installed it using pip install.

So I would request you to kindly help me ASAP @ccordoba12 sir.

Once again, I apologize for the inconvenience caused.

Thanks and Best,
Sai...

**Comment by ccordoba12** [comment]
And please remove the directory

    C:\Users\HONEY\.spyder

That could fix this problem too.

**Comment by sgolestanian** [comment]
I‘m having same issue but with anaconda3 and spyder 4.0.1

**Comment by acibiber53** [comment]
I had the same issue with spyder 4.0.1. It was working with 3.3.6. I updated the anaconda, conda and spyder. It still didn't work.

What solved the problem for me was the ccordoba12's comment. I removed the directory at C:\Users\[Username]\.spyder-py3. @sgolestanian you might want to try that.

**Comment by honey09280** [comment]
I had this issue in the past,

What I did is that, I uninstalled it and reinstalled it.

While installing, it asked me if software is supposed to be available for
all users or only administrator. I selected all users.

Then it started working properly for me.



________________________________________

Sai Prakash Reddy Konda(Sai)
Graduate Student
Dept. of Electrical Engineering
University of Victoria
Ph: 250-588-2876
Email: reddyprakash092@gmail.com

**Comment by sgolestanian** [comment]
I Just downgraded to spyder 3.3.6 and I’m waiting for spyder 4.1 .
