### ISSUE TITLE
The texts in spyder ide are not showing properly

### ISSUE THREAD

**Issue by HuntFeng** [spyder-ide/spyder#9901]
I am using Windows Subsystem for Linux. Anaconda was freshly installed by following the instructions in this link 
[https://docs.anaconda.com/anaconda/install/](url)
Everything works good, except the texts in spyder ide are not showing properly, looks like I lack of some necessary fonts. (But the spyder is working fine, I can use it to plot graph and do computations, etc.)

![spyder](https://user-images.githubusercontent.com/33592421/61990365-0575d480-aff4-11e9-82cf-514564d505ea.PNG)

* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows Subsystem for Linux (Ubuntu)

**Comment by ccordoba12** [comment]
> I am using Windows Subsystem for Linux

Sorry but this is not a platform we support at the moment, and I have no idea why this error is showing up for you (it has never been reported before).
