### ISSUE TITLE
Figures will not plot inline

### ISSUE THREAD

**Issue by cadop** [spyder-ide/spyder#9906]
### What steps will reproduce the problem?

Spyder Python 3.7 on Windows 10 x64

Matplotlib always creates an external figure (including when using "inline"). Changes graphics settings does not change results. 

Same code and machine using Spyder Python 2.7 works correctly. 
Both using fresh install from Anaconda downloaded same day. 

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by cadop** [comment]
the Qt ironpython console works. Reinstalled matlab and it started somewhat plotting inline.  However it opens matplotlib figure windows during execution, then waits until the script finishes and moves all the figures inline.

**Comment by cadop** [comment]
Using block=True forces the plot to be outside of the console, so it is not resolved as I had thought.

**Comment by ccordoba12** [comment]
Sorry but this looks like a bug in Matplotlib and not in Spyder.

Besides

> the Qt ironpython console works. Reinstalled matlab and it started somewhat plotting inline

We don't use any of these packages.

**Comment by cadop** [comment]
What I meant with qt was based on the spyder doc that said to try the qt console. I did that, and it plots inline like it should, so it wasn't matplotlib that was causing it
