### ISSUE TITLE
# in a string confuses spyder

### ISSUE THREAD

**Issue by eliadb** [spyder-ide/spyder#9909]
### What steps will reproduce the problem?

Press enter after this line:

fig = plt.figure( figsize=(6.4,3.6), facecolor = '#f1f1f1' )

The indentation will be wrong since spyder does not see the right
pranthesis.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.11.3
* PyQt5 version: 5.11.3
* Operating System: Linux 4.19.0-5-amd64

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  5.8.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known issue and we'll try to fix it in Spyder 4, to be released in a couple of months.
