### ISSUE TITLE
iPython console crashs Spyder4.0.0b3 when using netCDF4

### ISSUE THREAD

**Issue by stavna** [spyder-ide/spyder#9911]
## Problem Description
Spyder 4.0.0b3 crashes when loading and using netCDF4 package within the iPython Console. Does not happen with the editor.

### What steps reproduce the problem?
1. import netcdf4
2. Only in the iPython console -> when typing "netcdf4.Dataset( " the exact same moment as you type the first bracket the IDE crashes and the ubuntu crashes with it.

### What is the expected output? What do you see instead?
Instead of opening the function description window the whole thing crashes and takes the ubuntu OS with it.

--- Note ---
I'm running spyder4.0.0b3 via x11 forwarding from our dept. server. Previous versions of Spyder always worked perfectly and smoothly with zero errors.

My local machine runs Ubuntu 18.04.2 LTS
The server's machine is 	CentOS Linux release 7.4.1708

## Versions
* Spyder version: Spyder 4.0.0b3 
* Python version: Python 3.7.3 64-bit
* Qt version: Qt 5.9.7 
* PyQt version: PyQt5 5.9.2 
* Operating System nQt 5.9.7 ame/version: Linux 3.10.0-693.5.2.el7.x86_64 

### Dependencies
```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
psutil >=0.3      :  5.6.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. How did you install Spyder and netcdf4?

**Comment by stavna** [comment]
Thanks for the quick reply!
I installed Spyder as such;
conda update qt pyqt
conda install -c spyder-ide spyder=4.0.0b3
(as instructed here - https://github.com/spyder-ide/spyder/releases/tag/v4.0.0b3)


and as for the netCDF4

conda install netcdf4


Stav

**Comment by stavna** [comment]
We're you able to reproduce the error?

**Comment by ccordoba12** [comment]
We'll take a look at it for beta5 because beta4 (to be released this week) is almost ready.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one to see if you can reproduce it.

**Comment by stavna** [comment]
Cheers, I'll keep following the thread and if anything comes up I'll keep u updated
thanks for the hard work!

**Comment by dalthviz** [comment]
I think the problem here was the calltip being to wide (do the wrapping not working correctly). @stavna could you try to check if the changes made in PR #9925 fix the issue? Thanks :)

**Comment by stavna** [comment]
There's actually a strange behaviour with the calltip, it works in the console but not in the editor. I think it worked a few days ago but not anymore

+ excuse my ignorance but how do I pull your version to the #9925 fix to my anaconda env?

**Comment by ccordoba12** [comment]
Please wait until beta4 is released (in a couple of days) to see if PR #9925 really fix your problem.

**Comment by stavna** [comment]
Will do, thanks!

**Comment by stavna** [comment]
issue fixed in spyder4.0.0b4 

Cheers!

**Comment by ccordoba12** [comment]
Great!! Thanks a lot for letting us know about it.
