### ISSUE TITLE
Preferences do not fully reset (transient.ini)

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9914]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
It seems like the preferences does not fully reset when calling `--reset`. More specifically, the file `transient.ini` seems to be kept. Now, given that name and that it seems like there has been some major changes to the configuration system it may very well be a transient.

When working on the bookmark stuff, I have changed the bookmarks to linebased, so no column information. Once starting master, spyder couldn't start since there was only one value, not two, in the bookmark information. 

This will off course not happen to regular users, but when I tried doing a --reset it didn't help, but I had to look around in the files and found transient.ini.

Of course, it would be good with a robust startup, but it will not be a problem going in the other direction (the column value is just dropped, apart from the fact that there wasn't any actual way to add bookmarks merged into master). Still, wanted to check what the status of transient.ini is. If it should stay, and in that case, shouldn't it be reset?

### What steps reproduce the problem?

Requires a bit of hacking to happen.

### What is the expected output? What do you see instead?

Everything is reset to a startable state.

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Linux 3.10.0-957.21.3.el7.x86_64 

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
Thanks for reporting! Will fix it :-)

**Comment by goanpeca** [comment]
I forgot to add the deletion of these files on reset. Will push a PR soon!

Thanks for testing @oscargus
