### ISSUE TITLE
Settings not getting applied

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#9915]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Tried basic troubleshooting (if a bug/error)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

![settings](https://user-images.githubusercontent.com/16781833/62096316-e328c480-b248-11e9-8ecb-7d2fd8d776c5.gif)

### What steps reproduce the problem?

1. Change some preferences (without triggering a restart).
2. The new settings doesn't get applied

## Versions

* Spyder version: 4.0.0dev0
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by goanpeca** [comment]
@dalthviz will fix it!

**Comment by goanpeca** [comment]
@dalthviz is this only on the editor preferences?

**Comment by ccordoba12** [comment]
Great, thanks a lot @goanpeca!
