### ISSUE TITLE
Predefined code cell in template is not shown up in new file

### ISSUE THREAD

**Issue by phineas-pta** [spyder-ide/spyder#9919]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I use code cells a lot so I predefine code cells in template using `#%%` or `# %%`. But when I create new file, the code cells aren't here, there's only `#%` or `# %`

### What steps reproduce the problem? What do you see instead?

1. menu: Tools > Preferences > Editor > Advanced settings > Edit templates for new modules
2. add a code cell:
![image](https://user-images.githubusercontent.com/37548991/62119358-a946d500-b2bf-11e9-9c20-fb52b3055c7a.png)
3. create new file: the code cell definition disappears!
![image](https://user-images.githubusercontent.com/37548991/62119480-f9259c00-b2bf-11e9-8323-95acdb961c2d.png)

*workaround I found*: add an additional `%` or use `# <codecell>`

## Versions

* Spyder version: 3.3.6
* Python version: 3.6.8 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by bcolsen** [comment]
Thank you for the bug report!

This is an issue that I have had as well.  It results from using `%` to template the strings in the template. When #2884 gets implemented with python string templating, this problem will be solved.

I'm closing this in favor of #2884, but feel fee to join in the conversation on that thread. 

It looks fairly simple to implement if you want to give it a shot: 
https://github.com/spyder-ide/spyder/blob/b67cf68d6b9437899820ff895ac9e0523aeed13a/spyder/plugins/editor/plugin.py#L1647-L1678
