### ISSUE TITLE
Warning/error on last row not in warning list

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9924]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

If an error/warning is created on the last line of the file, it is shown in the editor, but does not show up in the menu (and therefore not in the pane I'm working on in #9836). Not a major issue (since most files should end with an empty line anyway, but still an issue (and I guess that code quality checks for that issue will not show up either). 

I also noted that the icons used are not the same as for the panel. Not sure if that is a bug or a feature though. (I aim at matching the editor panel icons in the pane).

![lastlinewarning](https://user-images.githubusercontent.com/8114497/62167249-18094a00-b323-11e9-9127-777ac10fd2f1.gif)

I can mention that I tried to sort it out, but simply iterating a few times more (by changing line 2072) didn't do the trick. So I do not expect that I will be able to solve it, hence posting this.
https://github.com/spyder-ide/spyder/blob/c188748789c8b069b5fc383061219f875fe36959/spyder/plugins/editor/widgets/codeeditor.py#L2063-L2079

Finally, can this dict:
https://github.com/spyder-ide/spyder/blob/c188748789c8b069b5fc383061219f875fe36959/spyder/plugins/editor/widgets/codeeditor.py#L1971-L1977
be defined in a single place so that it is possible to not have to redefine it when it should be used? I can move it there (as part of #9836), but may need suggestions where to put it. It is only used twice (second time in the pane), but if there is a well defined general place to put it, it may be better.

(Edit: Todos on the last row works, so no worries there.)

### What steps reproduce the problem?

1. Write something that generates a warning or error on the last line
2. Check the warnings menu/try to go to next/previous warning

### What is the expected output? What do you see instead?
The warning/error should be there.

(Maybe use consistent icon types.)

## Versions

* Spyder version: 4.0.0.dev0
* Python version: 3.7.3 
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.0 :  4.5.2 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
