### ISSUE TITLE
PyLS settings are not being applied live

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9933]
@andfoy, after PR #9704 the PyLS preferences are not being applied live (I just verified that, although I haven't noticed it before).

For example, you can go to the menu

    Source > Show code style warnings

and see that activating/deactivating that option doesn't do anything after PR #9704, whereas it shows/hides pycodestyle errors before that.

**Comment by andfoy** [comment]
@ccordoba12 I cannot reproduce this one. On my local machine, settings are being replaced.

**Comment by goanpeca** [comment]
On my machine I tried as well with hover hints and it was not being updated.

**Comment by andfoy** [comment]
I've tried also with hover hints, and it works as expected

**Comment by goanpeca** [comment]
With the latest master @andfoy 

![lsp](https://user-images.githubusercontent.com/3627835/62265372-857fae00-b3e9-11e9-87f9-db0d4e157fb6.gif)

**Comment by ccordoba12** [comment]
@goanpeca, this could have been fixed by PR #9936 because now I can't reproduce it. So I'm leaving this for beta5 in case it's still an issue.

**Comment by goanpeca** [comment]
>@goanpeca, this could have been fixed by PR #9936 because now I can't reproduce it. So I'm leaving this for beta5 in case it's still an issue.

I still does not work for me with the latest master 🤷‍♂

**Comment by ccordoba12** [comment]
What if you do

    python bootstrap.py --safe-mode

? That uses a clean set of preferences.

**Comment by goanpeca** [comment]
>python bootstrap.py --safe-mode

I get the same behavior.

- I open a file, hover on the import : Works!
- Disable hover hints: It works
- Enable hover hints: It does not work

**Comment by ccordoba12** [comment]
It's working fine for me in Python 2.7 as well.

@steff456, could you test this on your macOS? Thanks!

**Comment by steff456** [comment]
It is working fine in macOS with python 3.7 in the current version of master

**Comment by goanpeca** [comment]
How about python 2.7 ?

**Comment by ccordoba12** [comment]
Just for the record (I left this comment on issue #10144):

I found a very simple way to reproduce this: using two Spyder instances. The problem is serious because every time users change an LSP option in the second instance, its related services (completion and linting) stop working completely.
