### ISSUE TITLE
plt.ioff() not supressing figure generation with Qt5

### ISSUE THREAD

**Issue by Yoshi2112** [spyder-ide/spyder#9949]
Crosspost with matplotlib https://github.com/matplotlib/matplotlib/issues/14950#issue-475460075

## Problem Description
Usual behaviour for supressing matplotlib plots (by enabling plt.ioff()) no longer working since update to latest version of conda.

### What steps reproduce the problem?
```
import numpy as np
import matplotlib.pyplot as plt

x = np.random.rand(10)
y = np.random.rand(10)

plt.ioff()
plt.plot(x, y)
```
### What is the expected output? What do you see instead?
The above code should not produce a figure window, but it does - i.e. the call to plt.off() does not disable interactive mode, or Spyder ignores it and generates a figure window anyway.

Expected behaviour occurs when matplotlib support is disabled, or the "Inline" graphics backend is selected. Manually selecting Qt4 throws an error (apparently it won't run with Qt5?). Selecting Tkinter successfully suppresses figure generation, but does not generate the figure space when interactive mode is on, or plt.show() is called (the figure window appears, but frozen). I'd always used the "Automatic" option, which I'm guessing is Qt5. When that is selected, a figure window is generated regardless of the state of interactive mode.

## Versions
* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies
```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
Closing in favor of the referenced Matplotlib issue (I left a comment there).
