### ISSUE TITLE
Internal Problem

### ISSUE THREAD

**Issue by Michael-H777** [spyder-ide/spyder#9952]
### What steps will reproduce the problem?

I have absolutely no idea what happened, heres what i did: 
create a new project with existing directory, thats it. 

This directory is also a github repo, have .git folder
(i dont know if thats the reason)
Theres also a .vscode folder here since I always use vscode to open this folder. 
theres also a __pycache__ folder that i dont know how it gets there. 

### Traceback
```python-traceback
  File "C:\Users\Michael\spyder\spyder\plugins\projects\plugin.py", line 281, in _create_project
    self.open_project(path=path)
  File "C:\Users\Michael\spyder\spyder\plugins\projects\plugin.py", line 319, in open_project
    self.main.editor.get_open_filenames())
  File "C:\Users\Michael\spyder\spyder\plugins\projects\plugin.py", line 427, in set_project_filenames
    self.current_active_project.set_recent_files(recent_files)
  File "C:\Users\Michael\spyder\spyder\plugins\projects\api.py", line 76, in set_recent_files
    for recent_file in recent_files]
  File "C:\Users\Michael\spyder\spyder\plugins\projects\api.py", line 76, in <listcomp>
    for recent_file in recent_files]
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
```

## Versions

* Spyder version: 4.0.0.dev0 85d9548a0
* Python version: 3.7.4
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by Michael-H777** [comment]
Hello,

I will try my best to describe the problem, my setup and steps to re-create problem.

Setup: I used ‘git clone’ to install spyder to my C drive, then run ‘pip install spyder’, then I create a shortcut of bootstrap.py and put in my start menu, I always use that shortcut to lunch my spyder ide.

Problem: can’t create new project at all. New directory and existing directory doesn’t work. I tried creating with new/existing directory in both C and D drive, none of them works.

Step: lunch spyder IDE with my shortcut, click new projects, click create. Then spyder prompts it has encountered an internal problem.

FYI, when running pip install spyder, it installed spyder-kernels version 0.5, but spyder4 uses spyder-kernels version 1.4, which I had to manually upgrade with pip, hope you guys can fix it.

I am more than happy to assist to have this resolved, feel free to contact me when you need more information.
I know information I provided doesn’t help much, but that’s exactly what I did when the bug window came up.

Best of luck,

Michael

**Comment by ccordoba12** [comment]
> Setup: I used ‘git clone’ to install spyder to my C drive, then run ‘pip install spyder’, then I create a shortcut of bootstrap.py and put in my start menu, I always use that shortcut to lunch my spyder ide.

This is wrong. If you want to use Spyder from master, please follow our contributing guide

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md

Or if you want to install our latest beta for beta4, please simply run

    pip install -U --pre spyder

This is well documented in Releases page:

https://github.com/spyder-ide/spyder/releases
