### ISSUE TITLE
Code folding bug

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#9956]
## Problem
When a line of code in a function shows a line break, at this point, the entire function is folded and a bug occurs.
code like this:
![115D652E-801A-4ae5-93EE-B33A94DED625](https://user-images.githubusercontent.com/1759365/62437597-75aff300-b776-11e9-8746-4678f830ba51.png)
The last tow lines are not folded:
![image](https://user-images.githubusercontent.com/1759365/62437617-8c564a00-b776-11e9-952b-8c4c5509b8ad.png)
But when the line break is deleted, everything is ok.Code like this:
![image](https://user-images.githubusercontent.com/1759365/62437644-af80f980-b776-11e9-8656-3b1222aeaa61.png)

Everything is ok:
![image](https://user-images.githubusercontent.com/1759365/62437669-c7f11400-b776-11e9-89c0-8a2c323a364f.png)
## Versions

* Spyder version: 4.0.0b4
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: win7

**Comment by ccordoba12** [comment]
I noticed this too. We'll take a look at this for our next beta.

**Comment by leavor** [comment]
> I noticed this too. We'll take a look at this for our next beta.

Thank you and your team, the spyder is getting better and better. 
Especially the code hints and completion functions are much better than before.

**Comment by ccordoba12** [comment]
Thanks for your kind words!! We put a lot of effort on improving that in this version.

**Comment by Khalilsqu** [comment]
This bug also affects indentation guides, I modified the indentation guides in a merged PR so that they follow the same level and styling as code folding. If this big is resolved indentation guides should be updated accordingly.

**Comment by AliyevMpk** [comment]
Another problem I noticed with code folding is that all the commented lines after a function definition (outside of function - with no indentation) belong to the function and will fold with it; until a non-comment line.

This:
![code_folding_issue](https://user-images.githubusercontent.com/41693419/63785444-9dbdec80-c905-11e9-8142-a8babe4c2075.PNG)


Will fold like this:
![code_folding_issue_2](https://user-images.githubusercontent.com/41693419/63785376-82eb7800-c905-11e9-91aa-05594bde1cee.PNG)

**Comment by raphaelquast** [comment]
this seems to be persistent in V4.0rc2

... simple example that does not fold correctly after installing V4.0rc2:

```python
def some_function(x):
    adsf = [[1,2,3],
            [4,6,8]

    print('adsf')
    return x
```

**Comment by JohnRobson** [comment]
V4.0.0.dev0 has no code folding.
