### ISSUE TITLE
runcell function not executing selected code in Spyder 4.0.0 beta4

### ISSUE THREAD

**Issue by walternewzoo** [spyder-ide/spyder#9962]
## Problem Description
In spyder 4.0.0b4, when I select and run a part of a script, instead of the old behavior of executing the selected code (copy to ipython console, execute), a runcell function is now executed. This function call does not actually execute the selected code for me. In addition to fixing the new function call's behavior, I would like to be able to choose how Spyder behaves in this regard (maintain support for old behavior to option to copy + execute).

### What steps reproduce the problem?
1. start spyder4.0.0b4
2. select a part of an open python script, execute selection (ctrl + enter)

### What is the expected output? What do you see instead?
I would expected the selected code to be executed (e.g. a defined function to be callable, a defined variable to contain the assigned value), but instead nothing happens as a result of the runcell function.

## Versions
* Spyder version: 4.0.0b5
* Python version: 3.6.8
* Qt version: 1.9.0
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
> This function call does not actually execute the selected code for me

Please post a simple code example that `runcell` is not evaluating.

>  I would like to be able to choose how Spyder behaves in this regard (maintain support for old behavior to option to copy + execute)

Please go to

    Tools > Preferences > Editor > Run code

and select the option called

    Copy full cell contents ...

to get the old behavior.

**Comment by walternewzoo** [comment]
solved. Thanks for your help @ccordoba12 ! Appreciate it <3

**Comment by ccordoba12** [comment]
No problem! It would be nice if you would let us know the case where `runcell` fails though.

**Comment by mteora** [comment]
This post is very useful. I'm starting to learn python and I was blocked for this. Thanks a lot!

**Comment by HigorAnjos** [comment]
Thanks!

**Comment by onlyarshan** [comment]
hi i made a comprehensive youtube video with steps on how to solve this issue do check it out
link is below
https://youtu.be/8r2gMyt8BS8
