### ISSUE TITLE
In fresh Anaconda installation, Spyder does not start and reports Assertion failed: error not defined [0] (C:\ci\zeromq_1549025594292\work\src\err.cpp:383)

### ISSUE THREAD

**Issue by fnielsen** [spyder-ide/spyder#9964]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Anaconda's Spyder will not start

### What steps reproduce the problem?

A 
1. Start Spyder by pressing the spyder appication button in the interface

B
1. Start Spyder from cmd. 

### What is the expected output? What do you see instead?

Spyder starts

### Paste Traceback/Error Below (if applicable)

A. Nothing

B. Assertion failed: error not defined [0] (C:\ci\zeromq_1549025594292\work\src\err.cpp:383)

```python-traceback

No traceback.

```

## Versions

* The most recent Anaconda version
* Spyder version: 
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows.

IronPython was also installed on the computer.

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This is most probably an issue with your firewall or antivirus, so not directly a Spyder problem. Please deactivate them and try again.

If that fails, I don't have more advices to give you, sorry.

**Comment by mradultiw** [comment]
If you are using any proxy app like proxifier, than close it first and than try again, it'll work. I was also having exactly same issue.
