### ISSUE TITLE
Internal Python Language server error (again)

### ISSUE THREAD

**Issue by DemirTonchev** [spyder-ide/spyder#9965]
## Problem Description

pressing "tab" on a graph object from networkx gives the error. 
ran
```
conda update jedi
```
did not help

### What steps reproduce the problem?

1. import networkx as nx
2. G=nx.Graph()
3. G.<tab> 
error

## Versions

* Spyder version: 4.0.0b4
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Linux mint

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.0 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Closing because there's no error here we can work with.
