### ISSUE TITLE
Plotting with Tkinter on Mojave 10.14.6 causes a crash & log out

### ISSUE THREAD

**Issue by evangelos1** [spyder-ide/spyder#9969]
### Issue Report Checklist

* [yes ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [yes ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [yes ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [n/a ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [yes ] Tried basic troubleshooting (if a bug/error)
    * [yes ] Restarted Spyder
    * [yes ] Reset preferences with ``spyder --reset``
    * [no ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [yes ] Tried the other applicable steps from the Troubleshooting Guide
* [yes ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have been using Tkinter for plotting, to avoid the slow execution problem described in #2902 . This solution worked just fine for me, until the latest Mojave update 10.14.6. Since the update, when I create a plot and click on the plot window icon on the dock, the screen goes black for a second and the macOS login screen appears. After I log in, the windows of Anaconda Navigator and Spyder are gone and their icons are no longer present on the Dock. Activity Monitor however indicates that python is still running.

I have reproduced this problem a few times. I switched from Tkinter back to Qt5 and that solved the crash problem.

### What steps reproduce the problem?

1. Use Tkinter backend for plotting
2. Plot something (e.g. a bunch of random points, a line, whatever)
3. Click on the plot window icon on the macOS dock to view the plot.

### What is the expected output? What do you see instead?

I expected to see the plot, as was the case prior to the update to Mojave 10.14.6. Instead, the whole screen turns black for a second. Then the macOS login screen appears and asks for log in credentials.

### Paste Traceback/Error Below (if applicable)

Unfortunately the Spyder window is gone after I log back in so I don't know how to check for error messages.

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.0 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Darwin 18.7.0 (macOS Mojave 10.14.6)

### Dependencies

IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by ccordoba12** [comment]
Thanks for the detailed report. Unfortunately this is not a problem we can solve in Spyder.

You could report it in Matplotlib:

https://github.com/matplotlib/matplotlib

to see if the they know something about it.

**Comment by johnnybarrels** [comment]
Also on macOS Mojave 10.14.6

Exact same problem, except for me I get the crash as soon as I run a script/cell containing any tkinter functions that call a window.

Really ruined my weekend

**Comment by ccordoba12** [comment]
Please report this problem in Matplotlib, as I mentioned above.

**Comment by johnnybarrels** [comment]
Am I missing something?

Why would I report an issue with Tkinter to Matplotlib?

**Comment by ccordoba12** [comment]
They could know what's happening with that, if other users reported the same problem.

We certainly can't help you with this problem, so I really don't understand why you keep posting about it here.

**Comment by johnnybarrels** [comment]
1. The issue is with Tkinter, not Matplotlib, so no idea why you insist we
contact them, and
2. You clearly aren’t familiar with community forums are you? 😂

**Comment by ccordoba12** [comment]
> 1. The issue is with Tkinter, not Matplotlib, so no idea why you insist we
contact them

Please read the bug description with care:

* Title: "**Plotting** with Tkinter on Mojave 10.14.6 causes a crash & log out"
* First line of the description: "I have been using Tkinter for **plotting** ..."

If you don't want to report this in Matplotlib, fine by me. That's what I would do as a user affected by this problem, to see if they know what can be causing such an ugly crash.

> 2. You clearly aren’t familiar with community forums are you?

This is not a community forum, it's a place to report problems about Spyder.

----

Please don't continue with this argument if you don't have something productive to say.
