### ISSUE TITLE
Sorting is not right when viewing a list in the Variable Explorer

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#9973]
Problem Description:
Produced a simple list the list shows up in the variable explorer in the order produced. When looking at the list in the console the order is maintained when opening the list from within the variable explorer to view the elements the order is not maintained. 

What steps to reproduce the problem?
1. in the console x = list(range(0,100))
2. x enter in the console shows the number in order
3. x shows in the variable explorer in order
4. when selecting x in the variable explorer to be viewed in a table the order is not maintained index numbers are all over the place.

What is the expected output? What do you see instead?
the ordered list

Versions
Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10
* Spyder version: Spyder 4.0.0b4 

Dependencies
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

**Comment by ccordoba12** [comment]
Please post a screenshot of the result seen in the Variable Explorer.

**Comment by boazdori** [comment]
![spyder_list](https://user-images.githubusercontent.com/26312908/62550479-fe13be00-b872-11e9-9210-d48b4b8f415c.jpg)

**Comment by goanpeca** [comment]
@boazdori if you clic the `index` header an re-sort things. Does it get the right ordering?

**Comment by boazdori** [comment]
NoOn Aug 6, 2019 17:55, Gonzalo Peña-Castellanos <notifications@github.com> wrote:@boazdori if you clic the index header an re-sort things. Does it get the right ordering?

**Comment by ccordoba12** [comment]
@boazdori, thanks for the screenshot!

@dalthviz, this one is for you. I think it's related to changes you made to fix sorting in the Variable Explorer.
