### ISSUE TITLE
Completion stopped working after switching to "This is an external server"

### ISSUE THREAD

**Issue by cgycorey** [spyder-ide/spyder#9992]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The code completion stopped working after you apply  "This is an external server" and un-tick it again. 

### What steps reproduce the problem?

1. Go to Preference
2. Click on Completion and linting tab and go to Advanced
3. Click on  "This is an external server"  tick and click Apply.
4. Untick "This is an external server" and apply it again.
5. Type any word to activate completion.

### What is the expected output? What do you see instead?
Expected: the code completion should be as normal as before.
Actual: code completion stop working

## Versions
* Spyder version: 4.0.0b4
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

### Dependencies

pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one. We need to perform a validation when "This is an external server" is selected, by doing a request on the `address:port` saved in our Preferences to see if there really is a PyLS server listening there.

If not, we need to show a QMessageBox to users saying this

> It was not possible to connect to a Python Language Server listening in {address}:{port}. Please verify the provided information is correct and try again.

**Comment by ccordoba12** [comment]
Besides, if that validation fails we need to avoid creating a transport client for the external (which ends up consuming 100% CPU, by the way).

**Comment by ccordoba12** [comment]
After issue #10021 is solved, we need to perform the following validations:

* If users deactivate "Use stdio pipes to communicate with server" and press apply, we need to verify that there are values for IP address and port. If that's not the case, we need to display a QMessageBox with the following text:

    > You haven't provided the server address you want to connect to. Please introduce that information and try again.

    And then we need to activate again "Use stdio pipes to communicate with server".

* If users deactivate "Use stdio pipes to communicate with server", there are values for IP and port, and the IP is local (i.e. 127.0.0.1), then we need to verify if there's a service listening in that port by using this

    https://stackoverflow.com/questions/19196105/how-to-check-if-a-network-port-is-open-on-linux

    If that's not the case, we need to display a QMessageBox with the following text:

    > It appears there is no Python Language Server listening at {address}:{port}. Please verify that the provided information is correct and try again.

     And then we need to activate again "Use stdio pipes to communicate with server".

    If the previous validation is successful, we proceed to launch an LSP client that connects to that server.

* If the IP is remote, then we can't make the previous verification. So we need to trust that the information is correct and launch a client that tries to connect to the server.

* Finally, if users on Windows want to use an external server, we need to require a Spyder restart. Please also test if switching from stdio to tcp (without an external server) is possible on Windows or we also need to require a restart.
