### ISSUE TITLE
TypeError in Kite client

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#9993]
### What steps will reproduce the problem?

When I open up Spyder, after a while (a few seconds), the Issue reporter window pops up. It seems that there's something wrong with kite autocompletion

### Traceback
```python-traceback
  File "C:\Users\Amin\Anaconda3\envs\pmeal\lib\site-packages\spyder\plugins\completion\kite\client.py", line 135, in perform_request
TypeError: 'NoneType' object is not subscriptable
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.2
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@ma-sadeghi, thanks for reporting. Do you have Kite installed in your system?

@andfoy, please take a look at this one.

**Comment by ma-sadeghi** [comment]
@ccordoba12 yes, I have Kite installed.

**Comment by andfoy** [comment]
We're not preventing None responses to not be attended. I'll fix this
