### ISSUE TITLE
Suggestion: enable "Always show this dialog on a first file run" by default in the "Run configuration per file" dialog

### ISSUE THREAD

**Issue by lucatrv** [spyder-ide/spyder#9997]
The "Always show this dialog on a first file run" should be enabled by default for the following reasons. Most programs that I know always show optional dialogs until the user explicitly choose to hide them. This is to make sure that the user completely understands the dialog message and purpose. With the current behavior, new users may close the dialog too quickly without reading it carefully or understanding all available functionalities, and then never see it again. Enabling it by default, would still allow experienced users to hide it easily if not needed for them. I would suggest to enable this option by default in the coming Spyder 4.0.
Another suggestion for Spyder 4.0 would be to also enable the "Remove all variables before execution" option by default, as it is needed to fully simulate a script behavior when executed outside Spyder, but this maybe is just my preference.

**Comment by ccordoba12** [comment]
> The "Always show this dialog on a first file run" should be enabled by default

That was the behavior years ago but it was changed to simply file execution. We don't plan to come back to the previous behavior, sorry.

> Another suggestion for Spyder 4.0 would be to also enable the "Remove all variables before execution" option by default

This is going to be improved in Spyder 4 by executing files in their own namespace (see spyder-ide/spyder-kernels#131). With that there will be no need to activate "Remove all variables" by default.

**Comment by kienpham89** [comment]
this option is no longer shown in Spyder 6. Any idea where it was moved to?

**Comment by ccordoba12** [comment]
@kienpham89, it was removed.
